{"name": "test_login[locked_out_user-secret_sauce-False]", "status": "broken", "statusDetails": {"message": "AttributeError: 'LoginPage' object has no attribute 'get_error_message'", "trace": "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"17cec2b13a0f8145dc4a2c8e0dc301c2\")>, username = 'locked_out_user', password = 'secret_sauce', is_valid = False\n\n    @pytest.mark.ui\n    @pytest.mark.parametrize(\"username,password,is_valid\", [\n        (\"standard_user\", \"secret_sauce\", True),\n        (\"locked_out_user\", \"secret_sauce\", False),\n        (\"wrong_user\", \"wrong_pass\", False),\n    ])\n    def test_login(driver, username, password, is_valid):\n        login_page = LoginPage(driver)\n        login_page.open()\n        login_page.login(username, password)\n        if is_valid:\n            products_page = ProductsPage(driver)\n            assert products_page.is_loaded()\n        else:\n>           assert \"Epic sadface\" in login_page.get_error_message()\n                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE           AttributeError: 'LoginPage' object has no attribute 'get_error_message'\n\ntests/ui/test_ui_login.py:19: AttributeError"}, "parameters": [{"name": "username", "value": "'locked_out_user'"}, {"name": "password", "value": "'secret_sauce'"}, {"name": "is_valid", "value": "False"}], "start": 1749135050799, "stop": 1749135051117, "uuid": "6245b2bb-8c53-4293-a360-d99f28a8615f", "historyId": "fe45d763be177eff15634465ed761845", "testCaseId": "4781fd2326e41bcc4eaaa21f5fb7f5a6", "fullName": "tests.ui.test_ui_login#test_login", "labels": [{"name": "tag", "value": "ui"}, {"name": "parentSuite", "value": "tests.ui"}, {"name": "suite", "value": "test_ui_login"}, {"name": "host", "value": "MacBook-Pro-Nikita.local"}, {"name": "thread", "value": "20501-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.ui.test_ui_login"}]}